[project]
name = 'contract-v1'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.name-faktory]
path = 'contracts/name-faktory.clar'
clarity_version = 2
epoch = 2.5

[contracts.name-faktory-dex]
path = 'contracts/name-faktory-dex.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
